"""
Downloads the original benchmark instances used in Section 5.1.

Frangioni, Lawrinenko, Berndt and the 1064 "-exact-" planted instances are not
generated by this repository. They are the original instance files from the
P||Cmax repository of Akram, Maas, Sanders, Schreiber (2025), which also
provides their known optimal makespans (opt_known.txt). That repository has no
license file, so the instances are not redistributed here; this script fetches
them from a fixed commit, converts them to the format of all other datasets
and checks every file against pcmax_manifest.sha256.

  source : https://github.com/anon495351/pcmax
  commit : 7ce7488b8f5cb5006448945ae56faec45c2c10fe (2024-07-18)

Conversion: the original files start with "p p_cmax n m" (Frangioni: "m", "n"
on separate lines, CRLF line endings) and may end with a terminating 0. The
converted files contain
  line 1: m
  line 2: n
  line 3: p[1] p[2] ... p[n]
Only the files listed in the manifest are written (upstream Frangioni has five
additional files that are not part of the evaluation).

Usage:
  python Implementation/Test_Instances/fetch_pcmax.py
  python Implementation/Test_Instances/fetch_pcmax.py --tarball pcmax.tar.gz   # offline
"""
import argparse
import hashlib
import io
import sys
import tarfile
import urllib.request
from pathlib import Path

COMMIT = "7ce7488b8f5cb5006448945ae56faec45c2c10fe"
URL = f"https://codeload.github.com/anon495351/pcmax/tar.gz/{COMMIT}"
HERE = Path(__file__).resolve().parent
MANIFEST = HERE / "pcmax_manifest.sha256"

# local dataset directory -> directory inside the pcmax repository
SOURCE_DIR = {"frangioni": "benchmarks/frangioni/INSTANCES",
              "lawrinenko": "benchmarks/lawrinenko",
              "berndt": "benchmarks/berndt",
              "planted": "benchmarks/planted"}


def convert(text: str) -> str:
    tokens = text.split()
    if tokens[0] == "p":
        assert tokens[1] == "p_cmax", "unexpected header"
        n, m = int(tokens[2]), int(tokens[3])
        sizes = tokens[4:4 + n]
    else:
        m, n = int(tokens[0]), int(tokens[1])
        sizes = tokens[2:2 + n]
    assert len(sizes) == n, "fewer sizes than announced"
    return f"{m}\n{n}\n" + " ".join(str(int(x)) for x in sizes) + "\n"


def read_manifest() -> list:
    entries = []
    for line in MANIFEST.read_text().splitlines():
        digest, rel = line.split()
        entries.append((digest, rel))
    return entries


def main():
    ap = argparse.ArgumentParser(description="Download the original pcmax instances.")
    ap.add_argument("--tarball", type=Path,
                    help="use an already downloaded tarball of the commit instead of the URL")
    ap.add_argument("--force", action="store_true",
                    help="rewrite files that already exist with the correct hash")
    args = ap.parse_args()

    entries = read_manifest()
    todo = [(d, rel) for d, rel in entries if args.force or not (HERE / rel).exists()
            or hashlib.sha256((HERE / rel).read_bytes()).hexdigest() != d]
    print(f"{len(entries)} files in the manifest, {len(entries) - len(todo)} already present")
    if not todo:
        return

    if args.tarball:
        data = args.tarball.read_bytes()
    else:
        print(f"downloading {URL} ...", flush=True)
        with urllib.request.urlopen(URL) as response:
            data = response.read()

    prefix = f"pcmax-{COMMIT}/"
    wanted = {prefix + SOURCE_DIR[rel.split("/")[0]] + "/" + rel.split("/")[1]: (d, rel)
              for d, rel in todo}
    written, mismatched = 0, []
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        for member in tar:
            if member.name not in wanted:
                continue
            digest, rel = wanted.pop(member.name)
            text = tar.extractfile(member).read().decode()
            converted = convert(text).encode()
            if hashlib.sha256(converted).hexdigest() != digest:
                mismatched.append(rel)
                continue
            (HERE / rel).parent.mkdir(exist_ok=True)
            (HERE / rel).write_bytes(converted)
            written += 1

    print(f"{written} files written")
    if wanted or mismatched:
        for rel in sorted(r for _, r in wanted.values())[:5]:
            print(f"  missing in the tarball: {rel}")
        for rel in mismatched[:5]:
            print(f"  hash mismatch: {rel}")
        sys.exit(f"{len(wanted)} missing, {len(mismatched)} with wrong hash")


if __name__ == "__main__":
    main()
