"""
França benchmark generator (França, Gendreau, Laporte, Müller, 1994)

Generates 150 P||Cmax instances:
  - class     : U (uniform)
  - range     : [1, 100]
  - n         : 10, 50, 100, 500, 1000
  - m         : 5, 10, 25
  - instances : 10 per (n, m)

File name : U_1_{n:04d}_{m:02d}_{k}.txt
Format    : first line m, second line n, third line p[1] ... p[n]
Seed      : derived from the file name (MD5), hence reproducible.

The generated files are part of the repository; this script documents how they
were created (numpy's Generator does not guarantee the same stream across versions).
"""

import hashlib
import os
import numpy as np

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

N_VALUES = [10, 50, 100, 500, 1000]
M_VALUES = [5, 10, 25]
N_INSTANCES = 10
R_LOW, R_HIGH = 1, 100


def _seed(filename: str) -> int:
    return int(hashlib.md5(filename.encode()).hexdigest(), 16) % (2**32)


def generate_franca():
    written = 0
    for n in N_VALUES:
        for m in M_VALUES:
            for k in range(N_INSTANCES):
                filename = f"U_1_{n:04d}_{m:02d}_{k}.txt"
                rng = np.random.default_rng(_seed(filename))
                jobs = rng.integers(R_LOW, R_HIGH + 1, size=n)
                path = os.path.join(OUT_DIR, filename)
                with open(path, "w") as f:
                    f.write(f"{m}\n")
                    f.write(f"{n}\n")
                    f.write(" ".join(map(str, jobs)) + "\n")
                written += 1

    readme = os.path.join(OUT_DIR, "readme.txt")
    with open(readme, "w") as f:
        f.write("""\
---------------------------------------------------------------------------------
FRANCA BENCHMARK
Source: França, Gendreau, Laporte, Müller (1994), Computers & Operations Research.
The instances are generated by generate.py with the parameters of the original.

File name: "A_B_C_D_E.txt"
  A = class      : U (uniform)
  B = range      : 1  ([1, 100])
  C = jobs n     : 0010, 0050, 0100, 0500, 1000
  D = machines m : 05, 10, 25
  E = index      : 0-9

Format:
  line 1 : m (number of machines)
  line 2 : n (number of jobs)
  line 3 : p[1] p[2] ... p[n] (processing times, integer, uniform in [1, 100])

Total: 150 instances (5 x 3 x 10)

opt_known.txt: the three instances for which neither OPT was known nor the lower
bound max(ceil(sum p / m), p_max) certifies makespan/OPT <= 13/11, solved
exactly with solve_opt.py (Gurobi, optimality proven).
---------------------------------------------------------------------------------
""")

    print(f"Franca: {written} instances written to {OUT_DIR}/")


if __name__ == "__main__":
    generate_franca()
